name: build-openlane-sky130
on: [push]

jobs:
  test-lane-sobel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - shell: bash
        run: |
          echo "Submodules"
          echo $GITHUB_WORKSPACE
          git submodule init
          git submodule update
          tree $GITHUB_WORKSPACE
      - shell: bash
        run: |
          echo "Dependencies"
          sudo apt install ghdl
          pip3 install cocotb pillow numpy opencv-python
      - shell: bash
        working-directory: ./CocoTest/test/lane_sobel
        run: |
          echo "Run Tests"
          echo "make"

  hdlmake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - shell: bash
        run: |
          echo "Submodules"
          echo $GITHUB_WORKSPACE
          git submodule init
          git submodule update
          tree $GITHUB_WORKSPACE
      - shell: bash
        run: |
          echo "Dependencies"
          pip3 install hdlmake
      - shell: bash
        working-directory: ./CocoTest/project/lane_sobel/C4
        run: |
          hdlmake
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: hdlmake-files
          path: ./CocoTest/project/lane_sobel/C4/Makefile

  # bitstream:
  #   runs-on: ubuntu-latest
  #   needs: hdlmake
  #   container: theypsilon/quartus-lite-c5:18.1.docker0
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #     - run: echo "EDALIZE_LAUNCHER=el_docker" >> $GITHUB_ENV
  #     - run: git submodule init
  #     - run: git submodule update
  #     - name: Download hdlmake-files
  #       working-directory: ./CocoTest/project/lane_sobel/C4
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: hdlmake-files
  #     - name: make
  #       working-directory: ./CocoTest/project/lane_sobel_C4
  #       run: make


# example from: https://github.com/secworks/sha256
# jobs:
#   build-sha256:
#     runs-on: ubuntu-latest
#     env:
#       REPO : sha256
#       VLNV : secworks:crypto:sha256
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
#         with:
#           path: sha256
#       - run: echo "EDALIZE_LAUNCHER=el_docker" >> $GITHUB_ENV
#       - run: pip3 install fusesoc
#       - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
#       - run: fusesoc run --target=sky130 $VLNV

